### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by wofeifeileni** [JiayuanWang-JW/YOLOv8-multi-task#9]
Hello, I would like to know how long it took you to train 300 epochs with three RTX 4090 graphics cards. I tried to train the "yolov8-bdd-v4-one-drop-independent-s.yaml" model on a 4090 graphics card, but my batch can only be set to around 24, and the training speed is very slow, taking about forty minutes per epoch. I want to know if this is what it should be, or if my settings are inappropriate in some area.

**Comment by JiayuanWang-JW** [comment]
In our manuscript, we mentioned that we use three 4090 GPUs to train the model with 120 bs and 300 epochs. We spent around two and a half days to train. BTW, different imgsz values will affect the BS values.

**Comment by JiayuanWang-JW** [comment]
We spent around two and a half days training with three 4090 GPUs. I think your training speed is normal. You don't need to worry about that. 

BTW, different imgsz values will affect the BS values. If you set bigger imgsz, the cap of BS will be smaller.

**Comment by wofeifeileni** [comment]
I first set epochs=3 to ensure that the model can run smoothly in my environment. However, after training the first epoch, an error occurred. Following the error path, I found that you made some modifications to the code in the file 'ultralytics/yolo/engine/trainer. py' to adapt to multiple tasks, which is also where the error occurred. I hope to know how to solve it. I have not made any modifications to the code at present, but have only changed some paths and parameters in "bdd multi.yaml" and "train.py".
![微信图片_20231020000958](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/126314381/74334ccb-59c1-4cab-a8b8-c1e28dc750b8)

**Comment by JiayuanWang-JW** [comment]
I reproduced your problem when I set the "val=False". I think that "val=False" so that the evaluate metrics are None. I never set "val" to False before. Thanks for your feedback on this bug. I will fix it ASAP. If you want to use my code now. Please set "val=False". This setting will increase the training time needed. 

I will let you know after I fix this bug. Thanks again.

**Comment by JiayuanWang-JW** [comment]
@wofeifeileni I have fixed the bug. Please try again. If there are any issues, please do not hesitate to let me know. Thanks.

I uploaded a new [model.py](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/main/ultralytics/yolo/engine/model.py) and [trainer.py](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/blob/main/ultralytics/yolo/engine/trainer.py). 

No need to update the predictor_multi.py. That is the same as the previous version. I mistakenly deleted the previous version, so I uploaded it again.

**Comment by wofeifeileni** [comment]
Thank you for your prompt response. I updated your fixed code in my environment today, but there were some new issues during my training process, as shown in the figure. After the first error, I attempted to add a line of code "print (trainer. metrics)" to the "on_fit_epoch_end" function to print it out, but I couldn't find a solution.
![微信图片_20231020212327](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/assets/126314381/67093c26-6ba0-486b-8458-ea53f878913c)

**Comment by JiayuanWang-JW** [comment]
If you want to get the evaluation metrics, you can set "val=True" during training. No need to add more code. Please pay attention if you want to add any code. You should do lots of work to debug because I changed some data structures for some various based on YOLOv8 to implement the multi-task. Additionally, we did not provide the FPS test in the training process. You changed the training code, am I right? 

A reminder, if you change the content, some code needs to be debugged because the data structure is different between training, val and prediction. This is because the YOLOv8 different code extracts information from different files. Some from dataset.yaml, some from model.yaml. So there are different data structures between train, val and predict. I think you can add the FPS test to training. That is fine. If you want to add more functions, you need to spend some time to debug.

One more thing, we recommend setting "val=True" during training because the model decides whether to early stop by comparing evaluation results. Your referred terminal results look good. Please consider referring to it in your project as the final result. 
 

> Thank you for your prompt response. I updated your fixed code in my environment today, but there were some new issues during my training process, as shown in the figure. After the first error, I attempted to add a line of code "print (trainer. metrics)" to the "on_fit_epoch_end" function to print it out, but I couldn't find a solution. ![微信图片_20231020212327](https://user-images.githubusercontent.com/126314381/276943243-67093c26-6ba0-486b-8458-ea53f878913c.png)

**Comment by wofeifeileni** [comment]
In order to identify the problem, I downloaded the latest version of the code again, and only changed some parameters and paths in the "yaml"file. However, after training an epoch, I still encountered the same problem shown in the above image.
I am wondering if it is because Tensorboard is unable to analyze the data of "seg drivelbe" and "seg lane".

**Comment by JiayuanWang-JW** [comment]
Oh. If you use Tensorboard to analyze your results. My code couldn't support it. I never use Tensorboard. So you are right. Tensorboard is unable to analyze the data of "seg drivable" and "seg lane". 

If you can add this function, I would really appreciate it. I wish you can submit a pull request after implementing this function if you want. Let's improve this open-source repository together.

**Comment by eddyminer** [comment]
> Oh. If you use Tensorboard to analyze your results. My code couldn't support it. I never use Tensorboard. So you are right. Tensorboard is unable to analyze the data of "seg drivable" and "seg lane".
> 
> If you can add this function, I would really appreciate it. I wish you can submit a pull request after implementing this function if you want. Let's improve this open-source repository together.

Regarding this issue, how can I avoid Tensorboard to analyse the result, I just want to try this code and make everything works before modifying the model.

**Comment by JiayuanWang-JW** [comment]
@eddyminer @wofeifeileni Please follow this [Link](https://github.com/JiayuanWang-JW/YOLOv8-multi-task/issues/12#issuecomment-1783859840) to solve the problem of Tensorboard.

**Comment by eddyminer** [comment]
Thanks a lot for the fast reply. I stuck for this for some days.
